---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: main-app
spec:
  project: default
  source:
    repoURL: 'https://github.com/pavars/masters.git'
    path: cluster-state/local
    targetRevision: main
    directory:
      recurse: true
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true

---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cadvisor
spec:
  project: default
  source:
    repoURL: 'https://github.com/pavars/masters.git'
    path: cadvisor/base
    targetRevision: main
  destination:
    namespace: cadvisor
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true