apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- namespace.yaml
- projects.yaml
- repository.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/install.yaml
- applications.yaml

patchesStrategicMerge:
- argocd-cmd-params-cm-patch.yml
- argocd-repo-server.yaml # not needed for HA

namespace: argocd

images:
- name: quay.io/argoproj/argocd
  newName: quay.io/argoproj/argocd
  newTag: v2.6.4
