---
apiVersion: v1
kind: Secret
metadata:
  name: bitnami-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://charts.bitnami.com/bitnami
  name: bitnami
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: prometheus-community-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://prometheus-community.github.io/helm-charts
  name: prometheus-community
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://grafana.github.io/helm-charts
  name: grafana
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: podinfo-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://stefanprodan.github.io/podinfo
  name: podinfo
  type: helm

---
apiVersion: v1
kind: Secret
metadata:
  name: pavars-argocd-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/pavars/masters.git

---
apiVersion: v1
kind: Secret
metadata:
  name: cadvisor-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://github.com/google/cadvisor.git

---
apiVersion: v1
kind: Secret
metadata:
  name: aqua-helm-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  url: https://aquasecurity.github.io/helm-charts/
  type: helm
  name: aqua
