---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: argocd
  source:
    repoURL: 'https://github.com/pavars/masters.git'
    path: argocd/overlays/local
    targetRevision: main
  destination:
    namespace: argocd
    name: in-cluster
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
