apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
- ../../base

resources:
- argocd-app.yaml

patchesStrategicMerge:
- argocd-cm.yaml
- argocd-server-service.yaml

namespace: argocd
